name: build-test

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        profile: [debug, release]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Print Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Install and build
      run: |
        conan install conanfile.py --profile=.conan/profiles/${{ matrix.profile }} --build missing --install-folder build/${{ matrix.profile }}
        conan build conanfile.py --build-folder build/${{ matrix.profile }}
