name: conan

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Compilation
      run: |
        conan install conanfile.py --profile=.infrastructure/profiles/default --build missing --install-folder build/default
        conan build conanfile.py  --build-folder build/default
