name: pack

on:
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Print Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Create
      run: |
        conan create conanfile.py tarc/development --build=missing --profile=.conan/profiles/release
